"""Assembles the remote watchdog into a single self-contained script.

The lifecycle *policy* is owned by the core and inlined verbatim from
``core/policy.py`` so the remote guard and `gpu status` can never
disagree. The *provider actions* are injected by the adapter. Neither side
knows about the other.
"""

from __future__ import annotations

import base64
import json
import zlib
import secrets
from pathlib import Path
from typing import Optional

from ..core import policy as policy_module
from ..providers.base import WatchdogSpec

AGENT_REMOTE_PATH = "/opt/jambu/watchdog.py"
CONFIG_REMOTE_PATH = "/etc/jambu/watchdog.json"
STATE_REMOTE_PATH = "/var/lib/jambu/activity.json"
EVENTS_REMOTE_PATH = "/var/log/jambu/events.jsonl"
WATCHDOG_LOG_PATH = "/var/log/jambu/watchdog.log"

_HEADER = """#!/usr/bin/env python3
# Generated by jambu-gpu. Do not edit on the instance.
# Lifecycle policy is inlined from jambu_gpu/core/policy.py.
from __future__ import annotations
"""

_FUTURE_IMPORT = "from __future__ import annotations"

_FALLBACK_ACTIONS = '''
def provider_stop(ctx):
    raise RuntimeError("this provider supplied no stop action")


def provider_destroy(ctx):
    raise RuntimeError("this provider supplied no destroy action")
'''


def generate_token() -> str:
    """Shared secret protecting the watchdog's public control port."""
    return secrets.token_urlsafe(32)


def _strip_future(source: str) -> str:
    return "\n".join(
        line for line in source.splitlines() if line.strip() != _FUTURE_IMPORT
    )


def build_agent_source(actions_source: Optional[str] = None) -> str:
    """Return the full stdlib-only watchdog script."""
    policy_source = _strip_future(Path(policy_module.__file__).read_text())
    body_source = _strip_future((Path(__file__).parent / "agent_body.py").read_text())
    actions = _strip_future(actions_source) if actions_source else _FALLBACK_ACTIONS
    return "\n\n".join(
        [
            _HEADER,
            "# --- inlined: jambu_gpu/core/policy.py ---",
            policy_source,
            "# --- injected: provider actions ---",
            actions,
            "# --- inlined: jambu_gpu/watchdog/agent_body.py ---",
            body_source,
        ]
    )


def build_agent_config(
    *,
    provider: str,
    instance_id: str,
    token: str,
    port: int,
    interval_s: float,
    startup_grace_s: float,
    policy: "policy_module.PolicyConfig",
    created_at: float,
    watchdog_spec: Optional[WatchdogSpec] = None,
) -> dict:
    return {
        "provider": provider,
        "instance_id": instance_id,
        "token": token,
        "port": int(port),
        "interval_s": float(interval_s),
        "startup_grace_s": float(startup_grace_s),
        "created_at": float(created_at),
        "policy": policy.to_dict(),
        "env": dict(watchdog_spec.env) if watchdog_spec else {},
        "provider_context": dict(watchdog_spec.context) if watchdog_spec else {},
    }


def _b64(text: str) -> str:
    return base64.b64encode(text.encode()).decode()


def _b64_gz_block(text: str, width: int = 76) -> str:
    """Compressed, line-wrapped payload.

    The boot script travels inside a provider API field, so the ~29 KB agent is
    deflated to ~9 KB and wrapped, instead of riding on one enormous line.
    """
    blob = base64.b64encode(zlib.compress(text.encode(), 9)).decode()
    return "\n".join(blob[i : i + width] for i in range(0, len(blob), width))


def build_onstart_script(
    *,
    agent_source: str,
    agent_config: dict,
    runtime_start_command: str,
    runtime_env: Optional[dict] = None,
    watchdog_enabled: bool = True,
) -> str:
    """Bash executed on the instance right after the container comes up.

    Order matters: the watchdog starts FIRST so an instance whose model server
    fails to boot is still protected by idle/max_lifetime rules.
    """
    lines = [
        "#!/bin/bash",
        "# Generated by jambu-gpu",
        "set -u",
        # mkdir first: a failed `exec` redirect would kill a non-interactive shell.
        "mkdir -p /etc/jambu /var/lib/jambu /var/log/jambu /var/run/jambu /opt/jambu",
        "exec >> /var/log/jambu/onstart.log 2>&1",
        "date -u +'[%Y-%m-%dT%H:%M:%SZ] jambu onstart begin'",
    ]

    for key, value in (runtime_env or {}).items():
        lines.append(f"export {key}={_shell_quote(str(value))}")
        lines.append(f"echo {_shell_quote(f'{key}={value}')} >> /etc/jambu/runtime.env")

    if watchdog_enabled:
        decode = (
            "import base64,zlib;"
            f"open({AGENT_REMOTE_PATH!r},'wb').write("
            f"zlib.decompress(base64.b64decode(open('{AGENT_REMOTE_PATH}.b64','rb').read())))"
        )
        lines += [
            "",
            "# --- lifecycle watchdog (survives local CLI death) ---",
            f"echo {_b64(json.dumps(agent_config))} | base64 -d > {CONFIG_REMOTE_PATH}",
            f"chmod 600 {CONFIG_REMOTE_PATH}",
            "PYBIN=$(command -v python3 || command -v python)",
            'if [ -z "$PYBIN" ]; then',
            '  echo "jambu: no python interpreter in this image; watchdog NOT installed"',
            "else",
            f"  cat > {AGENT_REMOTE_PATH}.b64 <<'JAMBU_AGENT_EOF'",
            _b64_gz_block(agent_source),
            "JAMBU_AGENT_EOF",
            f'  "$PYBIN" -c {_shell_quote(decode)}',
            f"  rm -f {AGENT_REMOTE_PATH}.b64",
            f"  chmod 700 {AGENT_REMOTE_PATH}",
            f'  nohup "$PYBIN" -u {AGENT_REMOTE_PATH} >> {WATCHDOG_LOG_PATH} 2>&1 &',
            "  echo $! > /var/run/jambu/watchdog.pid",
            '  echo "jambu: watchdog started pid $(cat /var/run/jambu/watchdog.pid)"',
            "fi",
        ]

    lines += [
        "",
        "# --- model runtime ---",
        runtime_start_command,
        "date -u +'[%Y-%m-%dT%H:%M:%SZ] jambu onstart done'",
    ]
    return "\n".join(lines) + "\n"


def _shell_quote(value: str) -> str:
    return "'" + value.replace("'", "'\"'\"'") + "'"
